# Generated by Django 5.0.3 on 2024-04-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DecimalField(decimal_places=8, help_text='Frequency of Antenna', max_digits=10, verbose_name='Frequency [GHz]')),
                ('length_of_patch', models.DecimalField(decimal_places=6, help_text='Length of Antenna', max_digits=9, verbose_name='Lenght of Patch [mm]')),
                ('width_of_patch', models.DecimalField(decimal_places=6, help_text='Width of Antenna', max_digits=9, verbose_name='Width of Patch [mm]')),
                ('slot_length', models.DecimalField(decimal_places=3, help_text='Slot Length of Antenna', max_digits=6, verbose_name='Slot Length [mm]')),
                ('slot_width', models.DecimalField(decimal_places=3, help_text='Slot Width of Antenna', max_digits=6, verbose_name='Slot Width [mm]')),
            ],
        ),
    ]
